### ISSUE TITLE
[1.18] Outdated syntax in "Hunt and Gather" advancement override

### ISSUE THREAD

**Issue by vectorwing** [onVoid/CoppersDelight#5]
Hello! As of 1.18 onward, it seems Copper's Delight's override for the **Hunt and Gather** advancement is using an outdated syntax, which causes any item to be a valid trigger for it, as opposed to just knives.

It's easy to miss without datagen, but in 1.18, item conditions are just arrays of strings, without keys or curly braces.

**Outdated syntax:**
```json
"copper_knife": {
  "trigger": "minecraft:inventory_changed",
  "conditions": {
    "items": [
      {  
        "item": "coppersdelight:copper_knife" // remove "item":
      }  // remove curly braces
    ]
  }
}
```

**New syntax:**
```json
"copper_knife": {
  "trigger": "minecraft:inventory_changed",
  "conditions": {
    "items": [
      "coppersdelight:copper_knife"
    ]
  }
}
```

Hope it helps! ^^

**Comment by brdle** [comment]
Hey, thanks for letting me know of this issue. One question though:
It seems [your latest code for Farmer's Delight](https://github.com/vectorwing/FarmersDelight/blob/1.18.2/src/generated/resources/data/farmersdelight/advancements/main/craft_knife.json) is using the same outdated syntax? This is where I got the advancement to override from, so is this something you plan on fixing in the main mod? I will update Copper's Delight, but I want it to match the format of the original.

**Comment by brnbrd** [comment]
> Hello! As of 1.18 onward, it seems Copper's Delight's override for the **Hunt and Gather** advancement is using an outdated syntax, which causes any item to be a valid trigger for it, as opposed to just knives.
> 
> It's easy to miss without datagen, but in 1.18, item conditions are just arrays of strings, without keys or curly braces.
> 
> **Outdated syntax:**
> 
> ```json
> "copper_knife": {
>   "trigger": "minecraft:inventory_changed",
>   "conditions": {
>     "items": [
>       {  
>         "item": "coppersdelight:copper_knife" // remove "item":
>       }  // remove curly braces
>     ]
>   }
> }
> ```
> 
> **New syntax:**
> 
> ```json
> "copper_knife": {
>   "trigger": "minecraft:inventory_changed",
>   "conditions": {
>     "items": [
>       "coppersdelight:copper_knife"
>     ]
>   }
> }
> ```
> 
> Hope it helps! ^^

Hey, thanks for letting me know of this issue. One question though:
It seems [your latest code for Farmer's Delight](https://github.com/vectorwing/FarmersDelight/blob/1.18.2/src/generated/resources/data/farmersdelight/advancements/main/craft_knife.json) is using the same outdated syntax? This is where I got the advancement to override from, so is this something you plan on fixing in the main mod? I will update Copper's Delight, but I want it to match the format of the original.

**Comment by vectorwing** [comment]
It seems JSON Diff tricked my eyes, and I got it wrong. My bad... 😓

The actual new syntax involves an `"items"` array inside the original `"items"` array, and is the one FD is using right now. The "item" key isn't read anymore, which makes MC treat it as an empty condition. It's a weird change, to be honest. x)

```json
"flint_knife": {
  "trigger": "minecraft:inventory_changed",
  "conditions": {
    "items": [
      {
        "items": [
          "farmersdelight:flint_knife"
        ]
      }
    ]
  }
},
```

**Comment by brnbrd** [comment]
Thank you, I've updated the syntax now.
