### ISSUE TITLE
The Knife cannot be repaired with Copper Ingots in the anvil

### ISSUE THREAD

**Issue by Farcr** [onVoid/CoppersDelight#6]
![2022-08-19_22 32 09](https://user-images.githubusercontent.com/40238086/185702649-5ab589c7-1643-4590-a20e-e01c27253b8d.png)
Ignore the texture, it's from my personal pack, but the item is still from this mod

**Comment by brnbrd** [comment]
The knife isn't repairable because it isn't damaged. Hit something with it and then check.
However, this mod is discontinued anyways, and all support has been moved to [Delightful](https://www.curseforge.com/minecraft/mc-mods/delightful).
